### ISSUE TITLE
gpg: Sorry, no terminal at all requested - can't get input

### ISSUE THREAD

**Issue by vladzaets** [IJHack/qtpass#18]
Not working for me in both "native" and "pass" modes.

In "native git/gpg" I get this error – "gpg: Sorry, no terminal at all requested - can't get input". As I looked up in google I should remove "no-tty" string from gpg config file, but in my config there is no such string.
![error1](http://s04.radikal.ru/i177/1504/18/8d14f0a6e376.jpg)

After installing gpg2 and pointing gpg exec to "/usr/local/bin/gpg2", I get this error:
![error3](http://s018.radikal.ru/i507/1504/9f/a7b2208afdaf.png)

In "pass" mode the window just freezes.
![error2](http://s019.radikal.ru/i627/1504/19/3708213d1a48.jpg)

**Comment by rdoeffinger** [comment]
I think you are using a key with passphrase, so GPG must get that from you.
Since the terminal isn't connected to anywhere we use --no-tty (I think we really don't want to handle passphrase input from qtpass).
However in the version you use --use-agent is added as well.
But for some reason (looking at the output in the second screenshot) gpg-agent claims that you cancelled the passphrase input dialog.
I assume that you didn't in which case I suspect something i your setup breaks gpg-agent requesting the passphrase from you (I think it should normally call the pinentry tool).
So I suspect this issue somewhere in the setup far outside qtpass itself, maybe you can debug it further with this information?

**Comment by rdoeffinger** [comment]
Also, in pass mode I suspect it hangs because it tries to read the passphrase from the terminal, which is not connected. And lastly, I have tested key with both passphrases and keys on smartcards with PINs to work on Linux (default gpg setup) and Windows (gpg4win) at least, so it is at least not generally broken...

**Comment by annejan** [comment]
Unfortunately I can't test on OsX currently . . 
Can confirm passphrase and smartcard to work on Linux too.

**Comment by annejan** [comment]
Most of these issues are fixed, all except for one.

The freezing is caused by an upstream bug in pass when (in my case) using a GPG smart-card and not having it inserted.
I have a pull request waiting to fix this https://github.com/zx2c4/password-store/pull/14

**Comment by vladzaets** [comment]
I still experience all of this issues.

**Comment by annejan** [comment]
The second screenshot gives a hint.
Your gpg secret key cannot be found by the gpg sub-system.

Could you help me debugging this by giving me some more information on your setup?
Does pass (in the command line) work for you?
Is the password store initialized correctly?

Unfortunately the pass locking issue (third screenshot) is caused by pass itself, using my pass fork solved that issue for me.

It looks to me like there is something "wrong" with the execution environment that causes gpg to not find your secret key. I will have a deeper look into this, since I now have a mac OS environment to test in again, any information on your setup you can give will help me fix this issue.

**Comment by annejan** [comment]
Apparently using /usr/local/MacGPG2/bin/gpg2 as the pass executable in the configuration menu is a lot better than the /usr/local/bin/gpg . . 
![screen shot 2015-05-05 at 03 21 52](https://cloud.githubusercontent.com/assets/294470/7465721/59559520-f2d6-11e4-9bed-def04e4220bd.png)

**Comment by vladzaets** [comment]
Yes, the pass in the command line does work for me.

When I execute this command 'open /Users/vladislavzaets/Downloads/qtpass-master-2/QtPass.app' it still doesn't work.

I don't have such directory /usr/local/MacGPG2/

**Comment by annejan** [comment]
I am convinced it is a path issue in the QProcess, will have a deeper look tomorrow.
The development branch should now also work with gpg2 installed in /usr/local/bin
