### ISSUE TITLE
Invalid font color with Breeze Dark theme

### ISSUE THREAD

**Issue by vanyasem** [IJHack/QtPass#340]
I am running Arch GNU/Linux with KDE Plasma 5.11.4 (Qt 5.10.0)

I am using a dark theme (Breeze Dark), but unfortunately some fonts are rendered incorrectly and are impossible to read.

I tried both installing the package from repos and compiling it myself.

![2017-12-30-024057_1602x968_scrot](https://user-images.githubusercontent.com/13350458/34449627-157eacf6-ecf2-11e7-9fd0-486cabaa8730.png)

**Comment by daveol** [comment]
The same issue arises by enabling the "Global Dark Theme" in gnome 3 on fedora
![screenshot from 2018-02-02 16-41-46](https://user-images.githubusercontent.com/1355084/35741975-7c9ed034-0839-11e8-9b67-21fb8a79e028.png)

**Comment by annejan** [comment]
This should probably only use native theme colours instead of hardcoded colours.

**Comment by Piraty** [comment]
I can add to this.
In most parts of qtpass my dark theme is respected in terms of color inversion, but not on "welcome screen".
![qtpass_dark-theme_fail](https://user-images.githubusercontent.com/23238955/41087959-803dfd2a-6a3e-11e8-81c2-d00c3b5891eb.png)
I suspect the text colors are hardcoded.

**Comment by annejan** [comment]
Fixed the HTML
<img width="335" alt="screenshot 2018-06-28 at 11 26 37" src="https://user-images.githubusercontent.com/294470/42025967-3756f042-7ac6-11e8-8d50-10737fa7a607.png">
I don't like the blue, but I like adding hardcoded styles even less . .

Testing on KDE Breeze Dark asap 😸

**Comment by annejan** [comment]
In beta2 Apple disabled dark theme for any and all Qt applications . .

So will have to test and dev rest on KDE instead ;-)

**Comment by alxlg** [comment]
Can you please use system colors and not hard code any color?

**Comment by a-andreyev** [comment]
Hello! Thanks for the handy app!
Looks like it's possible just to drop the hardcoded `color:#0000ff` value at the `src/configdialog.ui` and `src/mainwindow.ui` to fix the issue, am I right? :thinking: 
Checking with Qt 5.13, KDE Plasma 5.16 (yet another arch fanboy), looks like html without specified color renders correctly according to the system-wide theme? (For example, at the config dialog version info)

![Imgur](https://i.imgur.com/OYwJt3V.png)
![Imgur](https://i.imgur.com/UbX3d2r.png)

**Comment by pheraph** [comment]
I still see this problem on macOS (QtPass 1.3.2). 🧐

<img width="430" alt="screen" src="https://user-images.githubusercontent.com/58503/67015071-34cd4680-f0f6-11e9-97f6-6b6453ad4395.png">

**Comment by Piraty** [comment]
the dark blue hyperlink color seems to be inherited from system/qt, since i have that in quiet a lot applications (along: texstudio, quassel)

**Comment by annejan** [comment]
This does not seem to be the case this time @Piraty
![Screenshot 2019-10-17 at 18 04 41](https://user-images.githubusercontent.com/294470/67026696-9dbdba00-f108-11e9-8775-78bdb08aa3d2.png)
I have sanitised the HTML content of the start screen.
Unfortunately QtCreator automagically places `<span>` the markup back . . @Piraty was right after all 😉 

So I edited the `mainwindow.ui` file and replaced the HTML for clean HTML . .

Now it looks like this (macOS dark) . . 
![Screenshot 2019-10-17 at 18 31 38](https://user-images.githubusercontent.com/294470/67028883-66e9a300-f10c-11e9-8938-6538cc2f505a.png)

So no improvement there . . except for size and spacing 😞

**Comment by annejan** [comment]
I'm taking this up with Qt . . Along with the inherited transparency of context menu's . .
![Screenshot 2019-10-17 at 18 39 24](https://user-images.githubusercontent.com/294470/67029384-79b0a780-f10d-11e9-8d8c-1f8c7651e96b.png)
