### ISSUE TITLE
macos: can't create new password

### ISSUE THREAD

**Issue by newcron** [IJHack/QtPass#66]
Hi Everyone, 
when I try to create a new password, (Macos 10.9.5, git version 1.9.3 (Apple Git-50), gpgtools 1.2b6 (1057b)), once I enter the password and press "OK" I get an error like 

```
error: pathspec '/Users/matthias.huttar/dev/atlas/password-store/asdfsdf.gpg' did not match any file(s) known to git.
```

and no file is created. am i doing something wrong here?

**Comment by annejan** [comment]
I'll have a look into this, it kind of looks like the password store is not initialised correctly.
This has to do with https://github.com/IJHack/qtpass/issues/57 and https://github.com/IJHack/qtpass/issues/55 too . .

Will look into this ASAP.

**Comment by cmol** [comment]
I am seeing the same problem at windows as well.

**Comment by annejan** [comment]
Are you using git?
Is the folder git initialised?

**Comment by cmol** [comment]
Yes I'm using git, but with a repo pre-cloned into .password-store. The funny thing is that our mac employees and myself at linux follows the same process of cloning the repo and using qtpass, but don't have the issue.

**Comment by annejan** [comment]
but you do have issues on windows . . 
and @newcron has them on mac .. I was more wondering about his issues on the mac, since I now made git a lot more optional (in the 0.9 versions)

**Comment by annejan** [comment]
@cmol in your case, is the path in the error message the actual path to the file?
And is it added to git? Do you use "native" mode or pass mode (via cygwin or something)?

**Comment by cmol** [comment]
@annejan it gives the full path to the file. 
    error: pathspec 'C:/Users/cmol/.password-store/test.com/wuhu.gpg' did not match any file(s) known to git.

This is both with starting QtPass with the launcher, and launching it from a git shell.

**Comment by cmol** [comment]
@annejan, do you have a working version on windows you could give me the output of a .git/config from?

I tried comparing from linux (initialized with pass), to windows but that didn't work.

**Comment by annejan** [comment]
This should be fixed by not using a .folder anymore . . 

Windows really really doesn't like folders starting with a .

**Comment by rapklein** [comment]
I am also not able to create a password under Win10, git 2.9.0, qtpass 1.1.3 . All it gives me is this message:
`error: pathspec 'C:/.../test.gpg' did not match any file(s) known to git.`
Could you explain how to fix?

**Comment by annejan** [comment]
@rapklein could it be that the password store is not initialised with git?
You could in the CMD try `git init` in the folder perhaps that helps.

I'll see if I can have a go at this on my Windows VM later this week . .

**Comment by djblue** [comment]
So I just had this same issue on Windows 10. I thought it was an issue with my git configuration, but when I copied the exact git config from a working qtpass on a linux machine, it still failed. I then tried disabling git and it still failed, but this time it was with a gpg error! So it turns out when I imported my gpg key into gpg4win I forgot to trust it. I was being so silly. Anyway, after I trusted the gpg key, everything worked perfectly!

I know this issue is closed, I just wanted to update it to help anybody else who runs into the same error message.

Thank you to all the contributors, this project is pretty sweet!

**Comment by annejan** [comment]
Might soon be made easier with a configuration option to always trust gpg keys . .
Relate issue #194

**Comment by alrayyes** [comment]
I have the same issue under Linux, also with a pre-cloned repo.

**Comment by alrayyes** [comment]
In my case I fixed it by changing my key trust to ultimate.

**Comment by rapklein** [comment]
Sorry for not following up on this earlier. Finally it was a key issue for me as well as not all of the multiple users were properly signed. The error messages should be improved though.
